name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/build
      - run: echo "Branch is $(git rev-parse --abbrev-ref HEAD)@$( git rev-parse HEAD)"
      - run: echo "Deploying to prod ..."



